fix: Temporarily pull helm dependencies using GH token to allow to pull deps from private Mermin repo

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -126,10 +126,16 @@ jobs:
       - name: Set up chart-testing
         uses: helm/chart-testing-action@v2.7.0
       - name: Install Helm dependencies
+        # TODO(Cleanup for GA): Drop authentication in "helm repo add" once repo is public
         run: |
-          helm repo add netobserv https://elastiflow.github.io/helm-chart-netobserv/
-          helm repo add opensearch https://opensearch-project.github.io/helm-charts/
-          helm dependency build charts/mermin
+          find charts -mindepth 1 -maxdepth 1 -type d | while read -r chart; do
+            echo Building for ${chart}
+            (helm dependency list ${chart} || true) | grep -E 'https://' | while read -r dep; do
+              helm repo add --username x-access-token --password ${{ secrets.GITHUB_TOKEN }} $(echo ${dep} | awk '{print $1}') $(echo ${dep} | awk '{print $4}')
+            done
+
+            helm dependency build ${chart}
+          done
       - name: Run chart-testing (list-changed)
         id: list-changed
         run: |
